name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: 54.95.167.79

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH config
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/id_rsa -r ./build ec2-user@${{ env.EC2_HOST }}:/home/ec2-user/
