name: Deploy to EC2 via Bastion Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add bastion host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 35.73.63.109 >> ~/.ssh/known_hosts

    - name: Add EC2 to known hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
            ssh -o StrictHostKeyChecking=no ec2-user@35.73.63.109 "ssh-keyscan 10.0.132.235" >> ~/.ssh/known_hosts

    - name: Deploy to EC2 via Bastion Host
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        scp -o ProxyCommand="ssh -W %h:%p ec2-user@35.73.63.109" -r ./build ec2-user@10.0.132.235:/home/ec2-user/
